service: auth-microservice
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: devProfile
  region: us-east-1
  environment:
    mongoUri: ${env:MONGODB_URI}
    UserPoolId: ${env:USER_POOL_ID}
    ClientId: ${env:CLIENT_ID}
    PoolRegion: ${env:POOL_REGION}
functions:
  signup:
    handler: src/functions/signup.handler
    events:
      - http:
          path: signup
          method: post
          cors: true
  signin:
    handler: src/functions/signin.handler
    events:
      - http:
          path: signin
          method: post
          cors: true
  verifyAuth:
    handler: src/functions/verifyAuth.handler
    events:
      - http:
          path: verify
          method: get
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
